# Generated by Django 4.2.13 on 2024-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "chat_message_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("chat_text", models.TextField()),
                ("chat_id", models.IntegerField()),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("user", "user"), ("agent", "agent")], max_length=6
                    ),
                ),
                ("time_stamp", models.DateTimeField()),
            ],
            options={
                "db_table": "Chat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistoryTitle",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("chat_name", models.CharField(max_length=255)),
                ("time_stamp", models.DateTimeField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "History_Title",
                "managed": False,
            },
        ),
    ]
